---
- name: Docker cont with ssh and nginx
  hosts: localhost
  gather_facts: false
  tasks:
    - name: build docker image
      docker_image:
        name: centos_ssh
        path: .
        state: present

    - name: run docker container
      docker_container:
        name: centos_ssh
        image: centos_ssh
        state: started
        detach: yes
        ports:
          - "2222:22"
          - "80:80"
        volumes:
          - ./html:/usr/share/nginx/html

    - name: install epel
      command:
        cmd: "docker exec centos_ssh yum install -y epel-release"

    - name: install nginx
      command:
        cmd: "docker exec centos_ssh yum install -y nginx"

    - name: enable nginx
      command:
        cmd: "docker exec centos_ssh systemctl enable nginx"

    - name: run nginx
      command:
        cmd: "docker exec centos_ssh nginx"

    - name: display resources
      command:
        cmd: "bash show_res.sh"
      become: yes
